name: smirl_timer
description: A simple timer app
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fluttericon: ^2.0.0
  google_fonts: ^3.0.1
  path_provider: ^2.0.10
  intl: ^0.17.0
  animated_flip_counter: ^0.2.4
  cupertino_icons: ^1.0.4
  get: ^4.6.5
  get_storage: ^2.0.3
  date_field: ^3.0.1
  counter_card:
    path: packages/counter_card

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
